services:
  frontend:
    build:
      context: ./client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./server/static:/app/static