# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  server:
    desc: Start server
    dir: server
    cmds:
      - npm install
      - npm run dev

  client:
    desc: Start client
    dir: client
    cmds:
      - npm install
      - npm run start

  dev:
    desc: Start server and client
    deps:
      - server
      - client